### ISSUE TITLE
The final version of the application does not work when using code from the course.

### ISSUE THREAD

**Issue by AdrianusWest** [neo4j-graphacademy/app-python#17]
The code in the repository on the githab and in the course module on the site is different. 

Registration and authorization do not work. I admit that I might have done something wrong. Below is the terminal output.

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/api/routes/auth.py", line 32, in login
    user = dao.authenticate(email, password)
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/api/dao/auth.py", line 107, in authenticate
    user = session.execute_read(get_user, email=email)
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 590, in execute_read
    return self._run_transaction(
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 523, in _run_transaction
    raise errors[-1]
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 480, in _run_transaction
    self._open_transaction(
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 388, in _open_transaction
    self._connect(access_mode=access_mode)
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 120, in _connect
    super()._connect(access_mode, **access_kwargs)
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/work/workspace.py", line 168, in _connect
    self._connection = self._pool.acquire(**acquire_kwargs_)
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 411, in acquire
    return self._acquire(
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 221, in _acquire
    return connection_creator()
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 138, in connection_creator
    connection = self.opener(
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 386, in opener
    return Bolt.open(
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_sync/io/_bolt.py", line 322, in open
    BoltSocket.connect(
  File "/home/adrian/PycharmProjects/Other/neo4j-graphacademy/app-python/neoflix/lib/python3.10/site-packages/neo4j/_async_compat/network/_bolt_socket.py", line 679, in connect
    raise ServiceUnavailable(
neo4j.exceptions.ServiceUnavailable: Couldn't connect to 3.239.35.134:7687 (resolved to ()):
Failed to read any data from server ResolvedIPv4Address(('3.239.35.134', 7687)) after connected
```

**Comment by adam-cowley** [comment]
That looks like a problem connecting to your database.  Did you get an email about your Sandbox being terminated?  Or if you completed the course, the database may have terminated automatically.

Try double-checking the details in your .env file with the values in the [Your Neo4j Sandbox](https://graphacademy.neo4j.com/courses/app-python/0-setup/2-sandbox/) lesson, or head to [Neo4j Sandbox and create a new Recommendations sandbox](https://sandbox.neo4j.com?usecase=recommendations).

**Comment by AdrianusWest** [comment]
Thanks! I'll try with a new instance of the sandbox, I think that's really the point.
